[翻译][news] Neofetch R.I.P
FOSScope/TranslateProject pull request #11
Opened 2024-05-02 17:09 UTC by excniesNIED

2024-05-02 17:14 UTC, Cubik65536 requested changes

2024-05-02 17:14 UTC, Cubik65536 commented on translated/news/240501-neofetch-rip.md
> +  作者：[SOURAV RUDRA](https://news.itsfoss.com/author/sourav/)
``` suggestion
  作者：[Sourav Rudra](https://news.itsfoss.com/author/sourav/)
```

请遵循大小写，以及以后请遵循 [commit message 标准](https://fosscope.com/wiki/fosscope-workflow/git-format#git-%E6%8F%90%E4%BA%A4%E4%BF%A1%E6%81%AF%E8%A7%84%E8%8C%83)

2024-05-02 17:50 UTC, Cubik65536 commented
下次注意

2024-05-02 17:50 UTC, merged

2024-05-03 01:14 UTC, excniesNIED commented
thx