[选题][news] 5 New Open Source Programming Languages That You Might Have Missed!
FOSScope/TranslateProject pull request #36
Opened 2024-07-19 08:57 UTC by excniesNIED

2024-07-19 14:47 UTC, Cubik65536 requested changes

2024-07-19 14:47 UTC, Cubik65536 commented on sources/news/20240713-5-new-open-source-programming-languages-that-you-might-have-missed.md
> +  - Programming Languages
用中文标签

2024-07-19 14:47 UTC, Cubik65536 commented on sources/news/20240713-5-new-open-source-programming-languages-that-you-might-have-missed.md
> +**Suggested Read** 📖
这部分不需要

2024-07-20 00:28 UTC, excniesNIED commented
已更正

2024-07-20 00:44 UTC, Cubik65536 approved these changes

2024-07-20 00:44 UTC, merged